### ISSUE TITLE
English?

### ISSUE THREAD

**Issue by boazcstrike** [Neos21/unlock-excel-book-password#7]
Hi,
Sorry to butt in,
I don't understand a single word on the readme even with google translate.. 
I understand the the codes tho // running it right now

Is it okay if you can give a summary/gist of the expected results?

Thank you!

GOOGLE TRANSLATE <broken japanese>:
こんにちは、
お尻申し訳ありません、
私もGoogle翻訳でのreadme上の単一の単語を理解していません..
今それを実行している//カントー私はコードを理解します

それはあなたが期待される結果の要約/要旨を与えることができれば大丈夫ですか？

ありがとうございました！

**Comment by Neos21** [comment]
コードを読めば理解はできるけど、README が日本語で書かれているから読めない、ということかしら。
英語苦手だけど頑張ってみます。

Do you need the English version of the README?
I have poor English, but I will try writing it in English.

**Comment by boazcstrike** [comment]
Yes! I need the English version if you have time, that would be very helpful.
Thank you!

GOOGLE TRANSLATE:
はい！私はあなたが時間があれば、それは非常に参考になる英語版が必要です。
ありがとうございました！
